"""Model-level invariants: FK enforcement, cascade/restrict, constraints.

These verify the schema decisions in ADR-0002/ADR-0008 hold at the database
level (SQLite enforces foreign keys only when the pragma is on, which the engine
sets), independent of any service-layer logic.
"""

import pytest
from sqlalchemy import Engine, inspect, select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from cairndex.domain.enums import FileRole, MediaKind
from cairndex.persistence.engine import ensure_content_indexes
from cairndex.persistence.models import AssetBundle, AssetFile, Tag


def _make_file(session: Session, bundle: AssetBundle, path: str) -> AssetFile:
    file = AssetFile(
        bundle_id=bundle.id,
        relative_path=path,
        original_filename=path.rsplit("/", 1)[-1],
        display_title=path.rsplit("/", 1)[-1],
        role=FileRole.PRIMARY_VIDEO,
        media_kind=MediaKind.VIDEO,
    )
    session.add(file)
    session.flush()
    return file


def test_ulid_primary_key_is_autogenerated(session: Session) -> None:
    bundle = AssetBundle(title="Untitled")
    session.add(bundle)
    session.flush()
    assert isinstance(bundle.id, str)
    assert len(bundle.id) == 26


def test_timestamps_are_timezone_aware(session: Session) -> None:
    bundle = AssetBundle(title="t")
    session.add(bundle)
    session.commit()
    session.refresh(bundle)
    assert bundle.created_at.tzinfo is not None


def test_foreign_key_violation_is_rejected(session: Session) -> None:
    # No such bundle: FK enforcement (PRAGMA foreign_keys=ON) must reject.
    orphan = AssetFile(
        bundle_id="00000000000000000000000000",
        relative_path="a.mp4",
        original_filename="a.mp4",
        display_title="a.mp4",
        role=FileRole.PRIMARY_VIDEO,
        media_kind=MediaKind.VIDEO,
    )
    session.add(orphan)
    with pytest.raises(IntegrityError):
        session.flush()


def test_deleting_bundle_cascades_to_files(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    file = _make_file(session, bundle, "movie/a.mp4")
    file_id = file.id
    session.commit()

    session.delete(bundle)
    session.commit()
    session.expire_all()

    # File row is gone (metadata-only); nothing on disk is touched.
    assert session.get(AssetFile, file_id) is None


def test_rating_out_of_range_is_rejected(session: Session) -> None:
    session.add(AssetBundle(title="bad", rating=6))
    with pytest.raises(IntegrityError):
        session.flush()


def test_same_file_cannot_be_linked_twice(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    _make_file(session, bundle, "movie/a.mp4")
    with pytest.raises(IntegrityError):
        _make_file(session, bundle, "movie/a.mp4")


def test_tag_adjacency_parent_child(session: Session) -> None:
    parent = Tag(name="genre")
    session.add(parent)
    session.flush()
    child = Tag(name="thriller", parent_id=parent.id)
    session.add(child)
    session.commit()

    loaded = session.scalar(select(Tag).where(Tag.id == parent.id))
    assert loaded is not None
    assert [c.name for c in loaded.children] == ["thriller"]
    assert child.parent is not None
    assert child.parent.name == "genre"


def test_ensure_content_indexes_readds_manual_order_columns(engine: Engine) -> None:
    # Simulate a library created before the manual-ordering columns existed by
    # dropping them, then prove the additive bootstrap patches them back in
    # (create_all never alters an existing table — see engine._ADDITIVE_CONTENT_COLUMNS).
    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE asset_bundles DROP COLUMN manual_order"))
        conn.execute(text("ALTER TABLE asset_bundle_collections DROP COLUMN sort_order"))

    inspector = inspect(engine)
    assert "manual_order" not in {c["name"] for c in inspector.get_columns("asset_bundles")}
    assert "sort_order" not in {
        c["name"] for c in inspector.get_columns("asset_bundle_collections")
    }

    ensure_content_indexes(engine)

    inspector = inspect(engine)
    assert "manual_order" in {c["name"] for c in inspector.get_columns("asset_bundles")}
    assert "sort_order" in {c["name"] for c in inspector.get_columns("asset_bundle_collections")}


def test_cover_file_id_is_nullable_and_settable(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    file = _make_file(session, bundle, "movie/a.mp4")
    bundle.cover_file_id = file.id
    bundle.primary_file_id = file.id
    session.commit()
    session.refresh(bundle)
    assert bundle.cover_file is not None
    assert bundle.cover_file.id == file.id
