"""Model-level invariants: FK enforcement, cascade/restrict, constraints.

These verify the schema decisions in ADR-0002/ADR-0008 hold at the database
level (SQLite enforces foreign keys only when the pragma is on, which the engine
sets), independent of any service-layer logic.
"""

import contextlib

import pytest
from sqlalchemy import Engine, inspect, select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session, sessionmaker

from cairndex.domain.enums import FileRole, MediaKind, ProposalKind
from cairndex.persistence.engine import _ADDITIVE_CONTENT_COLUMNS, ensure_content_indexes
from cairndex.persistence.models import (
    AssetBundle,
    AssetFile,
    GroupingPlan,
    GroupingProposal,
    Tag,
)


def _make_file(session: Session, bundle: AssetBundle, path: str) -> AssetFile:
    file = AssetFile(
        bundle_id=bundle.id,
        relative_path=path,
        original_filename=path.rsplit("/", 1)[-1],
        display_title=path.rsplit("/", 1)[-1],
        role=FileRole.PRIMARY_VIDEO,
        media_kind=MediaKind.VIDEO,
    )
    session.add(file)
    session.flush()
    return file


def test_ulid_primary_key_is_autogenerated(session: Session) -> None:
    bundle = AssetBundle(title="Untitled")
    session.add(bundle)
    session.flush()
    assert isinstance(bundle.id, str)
    assert len(bundle.id) == 26


def test_timestamps_are_timezone_aware(session: Session) -> None:
    bundle = AssetBundle(title="t")
    session.add(bundle)
    session.commit()
    session.refresh(bundle)
    assert bundle.created_at.tzinfo is not None


def test_foreign_key_violation_is_rejected(session: Session) -> None:
    # No such bundle: FK enforcement (PRAGMA foreign_keys=ON) must reject.
    orphan = AssetFile(
        bundle_id="00000000000000000000000000",
        relative_path="a.mp4",
        original_filename="a.mp4",
        display_title="a.mp4",
        role=FileRole.PRIMARY_VIDEO,
        media_kind=MediaKind.VIDEO,
    )
    session.add(orphan)
    with pytest.raises(IntegrityError):
        session.flush()


def test_deleting_bundle_cascades_to_files(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    file = _make_file(session, bundle, "movie/a.mp4")
    file_id = file.id
    session.commit()

    session.delete(bundle)
    session.commit()
    session.expire_all()

    # File row is gone (metadata-only); nothing on disk is touched.
    assert session.get(AssetFile, file_id) is None


def test_rating_out_of_range_is_rejected(session: Session) -> None:
    session.add(AssetBundle(title="bad", rating=6))
    with pytest.raises(IntegrityError):
        session.flush()


def test_same_file_cannot_be_linked_twice(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    _make_file(session, bundle, "movie/a.mp4")
    with pytest.raises(IntegrityError):
        _make_file(session, bundle, "movie/a.mp4")


# Directory keys follow every create and moved-file repair path assignment
def test_asset_file_directory_path_tracks_relative_path(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    file = _make_file(session, bundle, "movie/a.mp4")

    assert file.directory_path == "movie"
    file.relative_path = "archive/2026/a.mp4"
    assert file.directory_path == "archive/2026"


def test_tag_adjacency_parent_child(session: Session) -> None:
    parent = Tag(name="genre")
    session.add(parent)
    session.flush()
    child = Tag(name="thriller", parent_id=parent.id)
    session.add(child)
    session.commit()

    loaded = session.scalar(select(Tag).where(Tag.id == parent.id))
    assert loaded is not None
    assert [c.name for c in loaded.children] == ["thriller"]
    assert child.parent is not None
    assert child.parent.name == "genre"


# The columns ``grouping_proposals`` shipped with. Everything the model has
# beyond this set was added later, so it must also appear in
# ``engine._ADDITIVE_CONTENT_COLUMNS`` or an existing library never gains it.
_GROUPING_PROPOSAL_BASE_COLUMNS = frozenset(
    {
        "id",
        "plan_id",
        "parent_proposal_id",
        "target_bundle_id",
        "kind",
        "title",
        "directory",
        "confidence",
        "reason",
        "sort_order",
        "created_at",
        "updated_at",
    }
)


def test_every_later_grouping_column_is_patched_into_old_libraries() -> None:
    """Bind the model to the additive list, which nothing did before.

    ``create_all`` never alters an existing table and there is no migration
    chain, so a column added to the model has to be listed for the additive
    bootstrap too. The per-column tests below each name one column, so a model
    column missing from the list was never exercised — and shipped, producing
    "table grouping_proposals has no column named is_collection_context" on the
    first insert against a real library (owner-reported, 2026-08-13).

    This fails for *any* future column added to the model and not to the list.
    """
    from cairndex.persistence.base import Base

    model_columns = {c.name for c in Base.metadata.tables["grouping_proposals"].columns}
    listed = {c for table, c, _ in _ADDITIVE_CONTENT_COLUMNS if table == "grouping_proposals"}
    added_since_release = model_columns - _GROUPING_PROPOSAL_BASE_COLUMNS

    missing = added_since_release - listed
    assert not missing, (
        f"{sorted(missing)} are on GroupingProposal but not in _ADDITIVE_CONTENT_COLUMNS, "
        "so a library created before them will fail to insert a proposal"
    )
    # And the reverse, so the base set above cannot quietly rot.
    assert listed <= model_columns


def test_an_old_library_can_insert_an_addition_proposal(session: Session, engine: Engine) -> None:
    """The owner-reported failure, in its own shape: an addition proposal insert.

    A re-scan suggests new files into a confirmed bundle, and persisting that
    proposal is the first write that touches every column on the table.
    """
    with engine.begin() as conn, contextlib.suppress(Exception):
        conn.execute(text("ALTER TABLE grouping_proposals DROP COLUMN is_collection_context"))

    ensure_content_indexes(engine)

    plan = GroupingPlan(rule_version=1)
    session.add(plan)
    session.flush()
    session.add(
        GroupingProposal(
            plan_id=plan.id,
            kind=ProposalKind.BUNDLE,
            title="Studio Alpha - [2024.01.02] - A Long Release Style Name",
            directory="Genre/Studio Alpha",
            target_bundle_id="01JBUNDLEIDPLACEHOLDER0001",
            target_bundle_title="Studio Alpha - [2024.01.02] - A Long Release Style Name",
            confidence=0.8,
            reason="add 2 new file(s) to existing bundle",
        )
    )
    session.flush()

    stored = session.scalars(select(GroupingProposal)).one()
    assert stored.is_collection_context is False


def test_ensure_content_indexes_readds_manual_order_columns(engine: Engine) -> None:
    # Simulate a library created before the manual-ordering columns existed by
    # dropping them, then prove the additive bootstrap patches them back in
    # (create_all never alters an existing table — see engine._ADDITIVE_CONTENT_COLUMNS).
    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE asset_bundles DROP COLUMN manual_order"))
        conn.execute(text("ALTER TABLE asset_bundle_collections DROP COLUMN sort_order"))

    inspector = inspect(engine)
    assert "manual_order" not in {c["name"] for c in inspector.get_columns("asset_bundles")}
    assert "sort_order" not in {
        c["name"] for c in inspector.get_columns("asset_bundle_collections")
    }

    ensure_content_indexes(engine)

    inspector = inspect(engine)
    assert "manual_order" in {c["name"] for c in inspector.get_columns("asset_bundles")}
    assert "sort_order" in {c["name"] for c in inspector.get_columns("asset_bundle_collections")}


def test_ensure_content_indexes_adds_nullable_cover_frame_columns(engine: Engine) -> None:
    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE asset_files DROP COLUMN cover_time"))

    ensure_content_indexes(engine)

    columns = {c["name"]: c for c in inspect(engine).get_columns("asset_files")}
    assert columns["cover_time"]["nullable"] is True


# Existing libraries gain grouping-review edit metadata on open
def test_ensure_content_indexes_adds_grouping_proposal_edit_columns(engine: Engine) -> None:
    target_id = "01K00000000000000000000000"
    with Session(engine) as db:
        plan = GroupingPlan()
        proposal = GroupingProposal(
            plan=plan,
            kind=ProposalKind.CONTAINER,
            directory=f"@existing-collection/{target_id}",
        )
        db.add(proposal)
        db.commit()
        proposal_id = proposal.id

    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE grouping_proposals DROP COLUMN base_bundle_id"))
        conn.execute(text("ALTER TABLE grouping_proposals DROP COLUMN owner_edited"))
        conn.execute(text("ALTER TABLE grouping_proposals DROP COLUMN target_bundle_title"))
        conn.execute(text("ALTER TABLE grouping_proposals DROP COLUMN create_new_bundle"))
        conn.execute(text("ALTER TABLE grouping_proposals DROP COLUMN target_collection_id"))

    ensure_content_indexes(engine)

    columns = {c["name"] for c in inspect(engine).get_columns("grouping_proposals")}
    assert {
        "base_bundle_id",
        "owner_edited",
        "target_bundle_title",
        "create_new_bundle",
        "target_collection_id",
    } <= columns
    with engine.connect() as conn:
        restored_target = conn.scalar(
            text("SELECT target_collection_id FROM grouping_proposals WHERE id = :proposal_id"),
            {"proposal_id": proposal_id},
        )
    assert restored_target == target_id


# Existing libraries gain the durable per-directory stem levels on open. The
# column name predates the continuous dial and is deliberately unchanged: the
# model maps ``stem_level_overrides`` onto it, because nothing here can rename a
# column (there is no migration chain).
def test_ensure_content_indexes_adds_grouping_plan_stem_levels(engine: Engine) -> None:
    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE grouping_plans DROP COLUMN stem_modes"))

    ensure_content_indexes(engine)

    columns = {c["name"] for c in inspect(engine).get_columns("grouping_plans")}
    assert "stem_modes" in columns


# Existing libraries gain the additive bundle cursor table on open
def test_ensure_content_indexes_adds_bundle_cursor_table(engine: Engine) -> None:
    with engine.begin() as conn:
        conn.execute(text("DROP TABLE bundle_cursors"))

    ensure_content_indexes(engine)

    assert "bundle_cursors" in inspect(engine).get_table_names()


# Existing libraries gain a backfilled, indexed directory key on open
def test_ensure_content_indexes_adds_and_backfills_directory_path(engine: Engine) -> None:
    with sessionmaker(bind=engine, expire_on_commit=False)() as db:
        bundle = AssetBundle(title="legacy")
        db.add(bundle)
        db.flush()
        file = _make_file(db, bundle, "Show/S01/episode.mp4")
        file_id = file.id
        db.commit()

    with engine.begin() as conn:
        conn.execute(text("DROP INDEX ix_asset_files_directory_path"))
        conn.execute(text("ALTER TABLE asset_files DROP COLUMN directory_path"))

    ensure_content_indexes(engine)

    inspector = inspect(engine)
    columns = {c["name"] for c in inspector.get_columns("asset_files")}
    indexes = {i["name"] for i in inspector.get_indexes("asset_files")}
    assert "directory_path" in columns
    assert "ix_asset_files_directory_path" in indexes
    with engine.connect() as conn:
        directory = conn.scalar(
            text("SELECT directory_path FROM asset_files WHERE id = :id"), {"id": file_id}
        )
    assert directory == "Show/S01"


def test_cover_file_id_is_nullable_and_settable(session: Session) -> None:
    bundle = AssetBundle(title="b")
    session.add(bundle)
    session.flush()
    file = _make_file(session, bundle, "movie/a.mp4")
    bundle.cover_file_id = file.id
    bundle.primary_file_id = file.id
    session.commit()
    session.refresh(bundle)
    assert bundle.cover_file is not None
    assert bundle.cover_file.id == file.id


# A library that predates Date Opened gains the column, and every bundle in it
# reads back as never-opened — which is the truth: opens were not recorded then.
def test_ensure_content_indexes_adds_last_opened_at(engine: Engine) -> None:
    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE asset_bundles DROP COLUMN last_opened_at"))
    assert "last_opened_at" not in {c["name"] for c in inspect(engine).get_columns("asset_bundles")}

    ensure_content_indexes(engine)

    columns = {c["name"]: c for c in inspect(engine).get_columns("asset_bundles")}
    assert columns["last_opened_at"]["nullable"] is True
