"""subtitle tracks

Revision ID: 6a4414338fcc
Revises: 27eb9a803ffb
Create Date: 2026-06-26 12:32:52.198470+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a4414338fcc"
down_revision: str | None = "27eb9a803ffb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subtitle_tracks",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("bundle_id", sa.String(length=26), nullable=False),
        sa.Column("video_file_id", sa.String(length=26), nullable=True),
        sa.Column("source_file_id", sa.String(length=26), nullable=True),
        sa.Column("embedded_index", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("format", sa.String(length=32), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_forced", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(source_file_id IS NOT NULL) <> (embedded_index IS NOT NULL)",
            name=op.f("ck_subtitle_tracks_subtitle_one_source"),
        ),
        sa.CheckConstraint(
            "embedded_index IS NULL OR video_file_id IS NOT NULL",
            name=op.f("ck_subtitle_tracks_subtitle_embedded_has_video"),
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["asset_bundles.id"],
            name=op.f("fk_subtitle_tracks_bundle_id_asset_bundles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["asset_files.id"],
            name=op.f("fk_subtitle_tracks_source_file_id_asset_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["video_file_id"],
            ["asset_files.id"],
            name=op.f("fk_subtitle_tracks_video_file_id_asset_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subtitle_tracks")),
        sa.UniqueConstraint("source_file_id", name="subtitle_source_unique"),
        sa.UniqueConstraint("video_file_id", "embedded_index", name="subtitle_embedded_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subtitle_tracks")
    # ### end Alembic commands ###
