"""core schema

Revision ID: ca2034a94178
Revises:
Create Date: 2026-06-25 10:17:24.362564+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca2034a94178"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_bundles",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("cover_file_id", sa.String(length=26), nullable=True),
        sa.Column("primary_file_id", sa.String(length=26), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rating >= 0 AND rating <= 5", name=op.f("ck_asset_bundles_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["cover_file_id"],
            ["asset_files.id"],
            name=op.f("fk_asset_bundles_cover_file_id_asset_files"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["primary_file_id"],
            ["asset_files.id"],
            name=op.f("fk_asset_bundles_primary_file_id_asset_files"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_bundles")),
    )
    op.create_table(
        "folders",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("parent_id", sa.String(length=26), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folders.id"],
            name=op.f("fk_folders_parent_id_folders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folders")),
        sa.UniqueConstraint("parent_id", "name", name="parent_name"),
    )
    op.create_table(
        "smart_folders",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("filter_version", sa.Integer(), nullable=False),
        sa.Column("filter_json", sa.JSON(), nullable=False),
        sa.Column("default_sort", sa.String(length=64), nullable=True),
        sa.Column("default_layout", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_smart_folders")),
        sa.UniqueConstraint("name", name=op.f("uq_smart_folders_name")),
    )
    op.create_table(
        "storage_roots",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("canonical_path", sa.Text(), nullable=False),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE", "UNAVAILABLE", name="storagerootstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("scan_config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_roots")),
        sa.UniqueConstraint("name", name=op.f("uq_storage_roots_name")),
    )
    op.create_table(
        "tag_groups",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_tag_groups_name")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("parent_id", sa.String(length=26), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["tags.id"], name=op.f("fk_tags_parent_id_tags"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("parent_id", "name", name="parent_name"),
    )
    op.create_table(
        "asset_bundle_folders",
        sa.Column("bundle_id", sa.String(length=26), nullable=False),
        sa.Column("folder_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["asset_bundles.id"],
            name=op.f("fk_asset_bundle_folders_bundle_id_asset_bundles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
            name=op.f("fk_asset_bundle_folders_folder_id_folders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bundle_id", "folder_id", name=op.f("pk_asset_bundle_folders")),
    )
    op.create_table(
        "asset_bundle_tags",
        sa.Column("bundle_id", sa.String(length=26), nullable=False),
        sa.Column("tag_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["asset_bundles.id"],
            name=op.f("fk_asset_bundle_tags_bundle_id_asset_bundles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_asset_bundle_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bundle_id", "tag_id", name=op.f("pk_asset_bundle_tags")),
    )
    op.create_table(
        "asset_files",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("bundle_id", sa.String(length=26), nullable=False),
        sa.Column("storage_root_id", sa.String(length=26), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=1024), nullable=False),
        sa.Column("display_title", sa.String(length=1024), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "PRIMARY_VIDEO",
                "VIDEO_PART",
                "ALTERNATE_VERSION",
                "COVER",
                "IMAGE",
                "SCREENSHOT",
                "ALBUM_IMAGE",
                "SUBTITLE",
                "ATTACHMENT",
                "GENERATED_DERIVATIVE",
                "OTHER",
                name="filerole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "media_kind",
            sa.Enum(
                "VIDEO",
                "IMAGE",
                "SUBTITLE",
                "AUDIO",
                "OTHER",
                name="mediakind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "availability",
            sa.Enum("AVAILABLE", "MISSING", name="fileavailability", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("quick_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("full_hash", sa.String(length=128), nullable=True),
        sa.Column("tech_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["asset_bundles.id"],
            name=op.f("fk_asset_files_bundle_id_asset_bundles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["storage_root_id"],
            ["storage_roots.id"],
            name=op.f("fk_asset_files_storage_root_id_storage_roots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_files")),
        sa.UniqueConstraint("storage_root_id", "relative_path", name="root_path"),
    )
    op.create_table(
        "tag_group_memberships",
        sa.Column("group_id", sa.String(length=26), nullable=False),
        sa.Column("tag_id", sa.String(length=26), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["tag_groups.id"],
            name=op.f("fk_tag_group_memberships_group_id_tag_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_tag_group_memberships_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "tag_id", name=op.f("pk_tag_group_memberships")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag_group_memberships")
    op.drop_table("asset_files")
    op.drop_table("asset_bundle_tags")
    op.drop_table("asset_bundle_folders")
    op.drop_table("tags")
    op.drop_table("tag_groups")
    op.drop_table("storage_roots")
    op.drop_table("smart_folders")
    op.drop_table("folders")
    op.drop_table("asset_bundles")
    # ### end Alembic commands ###
