"""import records

Revision ID: bfa871853413
Revises: 6a4414338fcc
Create Date: 2026-06-26 13:01:16.312084+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa871853413"
down_revision: str | None = "6a4414338fcc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_records",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("bundle_id", sa.String(length=26), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["asset_bundles.id"],
            name=op.f("fk_import_records_bundle_id_asset_bundles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_records")),
        sa.UniqueConstraint("provider", "external_id", name="import_provider_external"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("import_records")
    # ### end Alembic commands ###
