"""Fresh disposable discovery-capable packages, never conversion of an existing owner library"""

import json
import shutil
from pathlib import Path

from cairndex.devtools.catalog_fixture import create_disposable
from cairndex.replicas.catalog.conversion import prepare_disposable
from cairndex.replicas.catalog.protocol import DISCOVERY_CAPABILITIES, CatalogDescriptor


# Package opt-in is limited to bytes generated by this fixture invocation
def create_discovery(*, parent: Path | None = None, playable: bool = False) -> Path:
    if playable:
        from cairndex.devtools.replica_media_fixture import create_playable

        root = create_playable(parent=parent, duration=18)
    else:
        fixture = create_disposable(parent=parent, bundles=3)
        root = prepare_disposable(fixture).package
        shutil.copytree(fixture.source / "Synthetic", root / "Synthetic")
    marker = root / ".cairndex/manifest.json"
    descriptor = CatalogDescriptor.model_validate(
        json.loads(marker.read_text())
        | {
            "format_version": 3,
            "catalog_version": 2,
            "minimum_reader": 3,
            "capabilities": DISCOVERY_CAPABILITIES,
        }
    )
    marker.write_text(descriptor.model_dump_json())
    return root
